configMapGenerator:
- files:
  - application.yml
  name: 82161545-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: "82161545"
images:
- name: ceappacr.azurecr.io/82161545
  newTag: "202411120850"
